In [ ]:
import pandas as pd
import requests
import io

In [ ]:
import pandas as pd
import requests
import io
size = 44679216
limit = size
offset = 0
url = f'https://www.datos.gov.co/resource/w9zh-vetq.csv?$limit={limit}&$offset={offset}'
response = requests.get(url)
if response.status_code == 200:
  chunk = response.text
  data = pd.read_csv(io.StringIO(chunk))
else:
    print(f"Error fetching data for offset {offset}: {response.status_code}")

data

,tipo_entidad,nombre_tipo_entidad,codigo_entidad,nombre_entidad,fecha_corte,tipo_de_persona,sexo,tama_o_de_empresa,tipo_de_cr_dito,tipo_de_garant_a,...,margen_adicional_a_la,montos_desembolsados,numero_de_creditos,grupo_etnico,antiguedad_de_la_empresa,tipo_de_tasa,rango_monto_desembolsado,clase_deudor,codigo_ciiu,codigo_municipio
0,1,BC-ESTABLECIMIENTO BANCARIO,55,Finandina,2023-06-30T00:00:00.000,Natural,Femenino,No aplica,Consumo,Sin garantia,...,0.0,8.181347e+08,528,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,BC-ESTABLECIMIENTO BANCARIO,55,Finandina,2023-05-19T00:00:00.000,Natural,Femenino,No aplica,Consumo,Sin garantia,...,0.0,1.137210e+08,1653,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,BC-ESTABLECIMIENTO BANCARIO,55,Finandina,2023-03-31T00:00:00.000,Natural,Femenino,No aplica,Consumo,Sin garantia,...,0.0,6.639253e+06,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,BC-ESTABLECIMIENTO BANCARIO,55,Finandina,2023-02-10T00:00:00.000,Natural,Masculino,No aplica,Consumo,Sin garantia,...,0.0,3.640913e+07,115,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,BC-ESTABLECIMIENTO BANCARIO,55,Finandina,2023-01-13T00:00:00.000,Natural,Femenino,No aplica,Consumo,Sin garantia,...,0.0,5.856296e+08,1368,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99434,1,BC-ESTABLECIMIENTO BANCARIO,39,Banco Davivienda,2023-04-07T00:00:00.000,Natural,Femenino,No aplica,Consumo,Sin garantia,...,0.0,1.710000e+09,12687,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99435,1,BC-ESTABLECIMIENTO BANCARIO,39,Banco Davivienda,2023-03-03T00:00:00.000,Natural,Femenino,No aplica,Consumo,Sin garantia,...,0.0,2.736131e+08,79,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99436,1,BC-ESTABLECIMIENTO BANCARIO,39,Banco Davivienda,2023-06-02T00:00:00.000,Natural,Masculino,No aplica,Consumo,Sin garantia,...,0.0,9.560000e+08,2746,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99437,1,BC-ESTABLECIMIENTO BANCARIO,39,Banco Davivienda,2023-01-27T00:00:00.000,Jurídica,No aplica,Pequeña empresa,Comercial ordinario,Garantía fondo nacional de garantías (FNG) o ...,...,0.0,5.000000e+06,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99438,1,BC-ESTABLECIMIENTO BANCARIO,39,Banco Davivienda,2023-01-27T00:00:00.000,Jurídica,No aplica,Mediana empresa,Comercial ordinario,Garantia idónea o no idónea,...,0.0,4.256547e+08,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#SOLAMENTE CORRER UNA VEZ POR SEMANA. ASEGURARSE DE ESTAR EN V28. TIEMPO ESTIMADO 35 MINUTOS

size = 44679216
limit = 10000
offset = 0
data = pd.DataFrame()


while(offset < size):
  url = f'https://www.datos.gov.co/resource/w9zh-vetq.csv?$limit={limit}&$offset={offset}'
  print(offset/size)
  response = requests.get(url)
  if response.status_code == 200:
    print("A")
    chunk = response.text
    print("B")
    datachunk = pd.read_csv(io.StringIO(chunk))
    print("C")
    data = pd.concat([data, datachunk], ignore_index=True)
  else:
      print(f"Error fetching data for offset {offset}: {response.status_code}")
  offset += limit

offset -=limit
limit = size - offset
url = f'https://www.datos.gov.co/resource/w9zh-vetq.csv?$limit={limit}&$offset={offset}'
response = requests.get(url)
chunk = response.text
datachunk = pd.read_csv(io.StringIO(chunk), engine = 'pyarrow')
data = pd.concat([data, datachunk], ignore_index=True)

data

0.0
A
B
C
0.00022381771425890732
A
B
C
0.00044763542851781465
A
B
C
0.000671453142776722
A
B
C
0.0008952708570356293
A
B
C
0.0011190885712945365
A
B
C
0.001342906285553444
A
B
C
0.0015667239998123513
A
B
C
0.0017905417140712586
A
B
C
0.002014359428330166
A
B
C
0.002238177142589073
A
B
C
0.0024619948568479805

<ipython-input-9-c9cf17848e83>:19: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  data = pd.concat([data, datachunk], ignore_index=True)

A
B
C

<ipython-input-9-c9cf17848e83>:19: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  data = pd.concat([data, datachunk], ignore_index=True)

0.002685812571106888
A
B
C

<ipython-input-9-c9cf17848e83>:19: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  data = pd.concat([data, datachunk], ignore_index=True)

0.002909630285365795
A
B
C

<ipython-input-9-c9cf17848e83>:19: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  data = pd.concat([data, datachunk], ignore_index=True)

0.0031334479996247026
A
B
C

<ipython-input-9-c9cf17848e83>:19: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  data = pd.concat([data, datachunk], ignore_index=True)

0.0033572657138836097
A
B
C

<ipython-input-9-c9cf17848e83>:19: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  data = pd.concat([data, datachunk], ignore_index=True)

0.003581083428142517
A
B
C

<ipython-input-9-c9cf17848e83>:19: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  data = pd.concat([data, datachunk], ignore_index=True)

0.0038049011424014243
A
B
C

<ipython-input-9-c9cf17848e83>:19: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  data = pd.concat([data, datachunk], ignore_index=True)

KeyboardInterrupt:

In [ ]:
data

,tipo_entidad,nombre_tipo_entidad,codigo_entidad,nombre_entidad,fecha_corte,tipo_de_persona,sexo,tama_o_de_empresa,tipo_de_cr_dito,tipo_de_garant_a,...,margen_adicional_a_la,montos_desembolsados,numero_de_creditos,grupo_etnico,antiguedad_de_la_empresa,tipo_de_tasa,rango_monto_desembolsado,clase_deudor,codigo_ciiu,codigo_municipio
0,1,BC-ESTABLECIMIENTO BANCARIO,55,Finandina,2023-06-30T00:00:00.000,Natural,Femenino,No aplica,Consumo,Sin garantia,...,0.0,8.181347e+08,528,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,BC-ESTABLECIMIENTO BANCARIO,55,Finandina,2023-05-19T00:00:00.000,Natural,Femenino,No aplica,Consumo,Sin garantia,...,0.0,1.137210e+08,1653,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,BC-ESTABLECIMIENTO BANCARIO,55,Finandina,2023-03-31T00:00:00.000,Natural,Femenino,No aplica,Consumo,Sin garantia,...,0.0,6.639253e+06,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,BC-ESTABLECIMIENTO BANCARIO,55,Finandina,2023-02-10T00:00:00.000,Natural,Masculino,No aplica,Consumo,Sin garantia,...,0.0,3.640913e+07,115,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,BC-ESTABLECIMIENTO BANCARIO,55,Finandina,2023-01-13T00:00:00.000,Natural,Femenino,No aplica,Consumo,Sin garantia,...,0.0,5.856296e+08,1368,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99434,1,BC-ESTABLECIMIENTO BANCARIO,39,Banco Davivienda,2023-04-07T00:00:00.000,Natural,Femenino,No aplica,Consumo,Sin garantia,...,0.0,1.710000e+09,12687,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99435,1,BC-ESTABLECIMIENTO BANCARIO,39,Banco Davivienda,2023-03-03T00:00:00.000,Natural,Femenino,No aplica,Consumo,Sin garantia,...,0.0,2.736131e+08,79,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99436,1,BC-ESTABLECIMIENTO BANCARIO,39,Banco Davivienda,2023-06-02T00:00:00.000,Natural,Masculino,No aplica,Consumo,Sin garantia,...,0.0,9.560000e+08,2746,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99437,1,BC-ESTABLECIMIENTO BANCARIO,39,Banco Davivienda,2023-01-27T00:00:00.000,Jurídica,No aplica,Pequeña empresa,Comercial ordinario,Garantía fondo nacional de garantías (FNG) o ...,...,0.0,5.000000e+06,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99438,1,BC-ESTABLECIMIENTO BANCARIO,39,Banco Davivienda,2023-01-27T00:00:00.000,Jurídica,No aplica,Mediana empresa,Comercial ordinario,Garantia idónea o no idónea,...,0.0,4.256547e+08,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
import pandas as pd
import requests
import io
size = 44679216
limit = size
offset = 0
url = f'https://www.datos.gov.co/resource/w9zh-vetq.csv?$limit={limit}&$offset={offset}'
response = requests.get(url)
if response.status_code == 200:
  chunk = response.text
  data = pd.read_csv(io.StringIO(chunk))
else:
    print(f"Error fetching data for offset {offset}: {response.status_code}")

data

In [ ]:
import pandas as pd
import requests
import io
import concurrent.futures

limit = 100000
size = 44679216
offsets = list(range(0, size, limit))
base_url = "https://www.datos.gov.co/resource/w9zh-vetq.csv"

def fetch_chunk(offset):
    url = f"{base_url}?$limit={limit}&$offset={offset}"
    response = requests.get(url)
    if response.status_code == 200:
        return pd.read_csv(io.StringIO(response.text), engine="pyarrow")
    return pd.DataFrame()

# Use multi-threading to speed up requests
dataframes = []
with concurrent.futures.ThreadPoolExecutor(max_workers=10) as executor:  # Adjust number of threads
    results = list(executor.map(fetch_chunk, offsets))

# Combine all dataframes
data = pd.concat(results, ignore_index=True)

KeyboardInterrupt:

In [ ]:
import pandas as pd
import numpy as np
from multiprocessing import Pool

# Function to clean and normalize data for each chunk
def clean_and_normalize(df_chunk):
    df_chunk = df_chunk
# Function to read data in chunks and process it in parallel
def open_in_chunks(file_name, chunk_size):
    chunks = pd.read_csv(file_name, chunksize=chunk_size)

    with Pool(4) as pool:  # Adjust the number of processes for your CPU
        # Process each chunk in parallel and combine results
        opened_data = pd.concat(pool.map(clean_and_normalize, chunks))

    return opened_data

data = open_in_chunks('drive/MyDrive/Sophomore Year/Asobancaria/datapi.csv', 100000)
data

Process ForkPoolWorker-2:
Process ForkPoolWorker-3:
Process ForkPoolWorker-1:
Process ForkPoolWorker-4:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
Traceback (most recent call last):
  File "/usr/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
Traceback (most recent call last):
  File "/usr/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.11/multiprocessing/pool.py", line 114, in worker
    task = get()
           ^^^^^
  File "/usr/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.11/multiprocessing/pool.py", line 114, in worker
    task = get()
           ^^^^^
  File "/usr/lib/python3.11/multiprocessing/queues.py", line 364, in get
    with self._rlock:
  File "/usr/lib/python3.11/multiprocessing/pool.py", line 114, in worker
    task = get()
           ^^^^^
  File "/usr/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.11/multiprocessing/queues.py", line 364, in get
    with self._rlock:
  File "/usr/lib/python3.11/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/multiprocessing/pool.py", line 114, in worker
    task = get()
           ^^^^^
KeyboardInterrupt
  File "/usr/lib/python3.11/multiprocessing/queues.py", line 364, in get
    with self._rlock:
  File "/usr/lib/python3.11/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/multiprocessing/queues.py", line 365, in get
    res = self._reader.recv_bytes()
          ^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
  File "/usr/lib/python3.11/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/multiprocessing/connection.py", line 430, in _recv_bytes
    buf = self._recv(4)
          ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/multiprocessing/connection.py", line 395, in _recv
    chunk = read(handle, remaining)
            ^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt

In [ ]:
#A PARTIR DE LA SEGUNDA VEZ CORRER ESTE CODIGO, TIEMPO ESTIMADO 4 MINUTOS
data = pd.read_csv('drive/MyDrive/Sophomore Year/Asobancaria/datapi.csv', engine ='pyarrow', usecols=['sexo'])
data = data.drop(columns=[ 'Unnamed: 0'])

In [ ]:
pd.set_option("display.max_columns", None)
original = data

def organizar(data, categoria1, categoria2, orden):
  if(orden == 'ascendiente' or orden == 'Ascendiente'):
    data = data.sort_values(by=[categoria1, categoria2])
    return(data)
  elif(orden == 'descendiente' or orden == 'Descendiente'):
    data = data.sort_values(by=[categoria1, categoria2], ascending=False)
    return(data)
def buscar (data, categoria, operador, especificador):
  if(operador == '='):
    data = data.loc[data[categoria] == especificador]
  elif(operador == '>'):
    data = data.loc[data[categoria] > especificador]
    data
  elif(operador == '<'):
    data = data.loc[data[categoria] < especificador]
    data
  elif(operador == '>='):
    data = data.loc[data[categoria] >= especificador]
    data
  elif(operador == '<='):
    data = data.loc[data[categoria] <= especificador]
    data
  return(data)
def guardar(data, nombre):
  data.to_csv('drive/MyDrive/Sophomore Year/Asobancaria/'+ nombre +'.csv')
def abrir(nombre):
  data = pd.read_csv('drive/MyDrive/Sophomore Year/Asobancaria/'+ nombre +'.csv')

In [ ]:
#Resetear el dataframe
data = original

In [ ]:
#Ejemplo Buscar, 10 segundos
encontrado = buscar(data, 'montos_desembolsados', '>', 100000)
data = encontrado
data

,tipo_entidad,nombre_tipo_entidad,codigo_entidad,nombre_entidad,fecha_corte,tipo_de_persona,sexo,tama_o_de_empresa,tipo_de_cr_dito,tipo_de_garant_a,producto_de_cr_dito,plazo_de_cr_dito,tasa_efectiva_promedio,margen_adicional_a_la,montos_desembolsados,numero_de_creditos,grupo_etnico,antiguedad_de_la_empresa,tipo_de_tasa,rango_monto_desembolsado,clase_deudor,codigo_ciiu,codigo_municipio
14317116,4,CF-COMPAÑÍA DE FINANCIAMIENTO,128,Nu Colombia C.F.,2025-03-14T00:00:00.000,Natural,Masculino,No aplica,Consumo,Sin garantia,Tarjeta de crédito para ingresos hasta 2 SMMLV,Consumos entre 7 y 12 meses,24.37,0.0,1740070.0,8,Ningún grupo étnico,No aplica(1),FS,Hasta 1 SMLMV,Deudor nuevo en la entidad,81.0,11001.0
14327628,4,CF-COMPAÑÍA DE FINANCIAMIENTO,128,Nu Colombia C.F.,2025-03-14T00:00:00.000,Natural,Masculino,No aplica,Consumo,Sin garantia,Tarjeta de crédito para ingresos hasta 2 SMMLV,Consumos entre 7 y 12 meses,24.54,0.0,101260.0,1,Ningún grupo étnico,No aplica(1),FS,Hasta 1 SMLMV,Deudor nuevo en la entidad,10.0,76823.0
14327772,4,CF-COMPAÑÍA DE FINANCIAMIENTO,128,Nu Colombia C.F.,2025-03-14T00:00:00.000,Natural,Masculino,No aplica,Consumo,Sin garantia,Tarjeta de crédito para ingresos hasta 2 SMMLV,Consumos entre 7 y 12 meses,24.54,0.0,101939.0,1,Ningún grupo étnico,No aplica(1),FS,Hasta 1 SMLMV,Deudor nuevo en la entidad,7111.0,5001.0
14327916,4,CF-COMPAÑÍA DE FINANCIAMIENTO,128,Nu Colombia C.F.,2025-03-14T00:00:00.000,Natural,Masculino,No aplica,Consumo,Sin garantia,Tarjeta de crédito para ingresos hasta 2 SMMLV,Consumos entre 7 y 12 meses,24.54,0.0,102719.0,2,Ningún grupo étnico,No aplica(1),FS,Hasta 1 SMLMV,Deudor nuevo en la entidad,10.0,25817.0
14328060,4,CF-COMPAÑÍA DE FINANCIAMIENTO,128,Nu Colombia C.F.,2025-03-14T00:00:00.000,Natural,Masculino,No aplica,Consumo,Sin garantia,Tarjeta de crédito para ingresos hasta 2 SMMLV,Consumos entre 7 y 12 meses,24.54,0.0,103100.0,1,Ningún grupo étnico,No aplica(1),FS,Hasta 1 SMLMV,Deudor nuevo en la entidad,4791.0,25175.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44440284,32,COOPERATIVAS DE CARÁCTER FINANCIERO,1,Cooperativa Financiera de Antioquia,2024-05-24T00:00:00.000,Natural,Femenino,No aplica,Consumo,Garantía fondo nacional de garantías (FNG) o ...,Consumo otros,Más de 3 años y hasta 5 años,30.90,0.0,8000000.0,1,Ningún grupo étnico,No aplica(1),FS,Mayor a 6 SMLMV menor o igual a 12 SMLMV,Deudor nuevo en la entidad,4771.0,5887.0
44440301,32,COOPERATIVAS DE CARÁCTER FINANCIERO,1,Cooperativa Financiera de Antioquia,2024-05-24T00:00:00.000,Natural,Femenino,No aplica,Consumo,Garantía fondo nacional de garantías (FNG) o ...,Consumo otros,Más de 3 años y hasta 5 años,30.90,0.0,40000000.0,1,Ningún grupo étnico,No aplica(1),FS,Mayor a 25 SMLMV menor o igual a 50 SMLMV,Deudor de la entidad,1313.0,5212.0
44555295,32,COOPERATIVAS DE CARÁCTER FINANCIERO,1,Cooperativa Financiera de Antioquia,2024-05-10T00:00:00.000,Natural,Femenino,No aplica,Consumo,Garantía fondo nacional de garantías (FNG) o ...,Consumo otros,Más de 5 años y hasta 7 años,31.53,0.0,30000000.0,1,Ningún grupo étnico,No aplica(1),FS,Mayor a 12 SMLMV menor o igual a 25 SMLMV,Deudor de la entidad,1410.0,5736.0
44555512,32,COOPERATIVAS DE CARÁCTER FINANCIERO,1,Cooperativa Financiera de Antioquia,2024-06-07T00:00:00.000,Natural,Femenino,No aplica,Consumo,Sin garantia,Libranza otros,Más de 3 años y hasta 5 años,23.19,0.0,2700000.0,1,Ningún grupo étnico,No aplica(1),FS,Mayor a 1 SMLMV menor o igual a 3 SMLMV,Deudor de la entidad,10.0,5212.0
44555519,32,COOPERATIVAS DE CARÁCTER FINANCIERO,1,Cooperativa Financiera de Antioquia,2024-06-07T00:00:00.000,Natural,Femenino,No aplica,Consumo,Garantia idónea o no idónea,Libre inversión,Más de 5 años y hasta 7 años,30.84,0.0,20000000.0,1,Ningún grupo étnico,No aplica(1),FS,Mayor a 12 SMLMV menor o igual a 25 SMLMV,Deudor de la entidad,6810.0,5736.0

In [ ]:
#Ejemplo organizar, 15-30 segundos
organizado = organizar(data, 'montos_desembolsados', 'sexo', 'ascendiente')
data = organizado
data

,tipo_entidad,nombre_tipo_entidad,codigo_entidad,nombre_entidad,fecha_corte,tipo_de_persona,sexo,tama_o_de_empresa,tipo_de_cr_dito,tipo_de_garant_a,producto_de_cr_dito,plazo_de_cr_dito,tasa_efectiva_promedio,margen_adicional_a_la,montos_desembolsados,numero_de_creditos,grupo_etnico,antiguedad_de_la_empresa,tipo_de_tasa,rango_monto_desembolsado,clase_deudor,codigo_ciiu,codigo_municipio
15826651,1,BC-ESTABLECIMIENTO BANCARIO,7,Bancolombia,2024-09-27T00:00:00.000,Natural,Masculino,No aplica,Consumo,Garantia idónea o no idónea,Sobregiro en cuenta corriente persona natural,Hasta 30 días,28.83,0.0,1.000000e+05,2,Sin información (1),No aplica(1),FS,Hasta 1 SMLMV,Deudor de la entidad,4731.0,25843.0
16973224,1,BC-ESTABLECIMIENTO BANCARIO,7,Bancolombia,2024-08-23T00:00:00.000,Natural,Masculino,No aplica,Consumo,Sin garantia,Sobregiro en cuenta corriente persona natural,Hasta 30 días,29.19,0.0,1.000001e+05,3,Ningún grupo étnico,No aplica(1),FS,Hasta 1 SMLMV,Deudor de la entidad,4721.0,11001.0
24038848,1,BC-ESTABLECIMIENTO BANCARIO,39,Banco Davivienda,2024-08-09T00:00:00.000,Natural,Masculino,No aplica,Consumo,Sin garantia,Tarjeta de crédito para ingresos superiores a ...,Consumos entre 19 y 24 meses,28.93,0.0,1.000001e+05,1,Sin información (1),No aplica(1),FS,Hasta 1 SMLMV,Deudor de la entidad,90.0,66170.0
1263060,1,BC-ESTABLECIMIENTO BANCARIO,7,Bancolombia,2023-10-20T00:00:00.000,Natural,Femenino,No aplica,Consumo,Sin garantia,Sobregiro en cuenta corriente persona natural,Hasta 30 días,39.79,0.0,1.000001e+05,2,Sin información (1),No aplica(1),FS,Hasta 1 SMLMV,Deudor de la entidad,9609.0,54001.0
16011151,1,BC-ESTABLECIMIENTO BANCARIO,7,Bancolombia,2024-11-22T00:00:00.000,Natural,Masculino,No aplica,Consumo,Sin garantia,Sobregiro en cuenta corriente persona natural,Hasta 30 días,27.88,0.0,1.000002e+05,3,Sin información (1),No aplica(1),FS,Hasta 1 SMLMV,Deudor de la entidad,4799.0,54498.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
376174,1,BC-ESTABLECIMIENTO BANCARIO,7,Bancolombia,2022-10-07T00:00:00.000,Natural,Masculino,No aplica,Consumo,Sin garantia,Libre inversión,Más de 3 años y hasta 5 años,31.37,0.0,1.203573e+11,8912,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32689538,1,BC-ESTABLECIMIENTO BANCARIO,39,Banco Davivienda,2023-01-27T00:00:00.000,Natural,Femenino,No aplica,Consumo,Sin garantia,Tarjeta de crédito para ingresos superiores a ...,Consumos a un mes,0.44,0.0,1.240557e+11,442733,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33293402,1,BC-ESTABLECIMIENTO BANCARIO,39,Banco Davivienda,2022-08-26T00:00:00.000,Natural,Masculino,No aplica,Consumo,Sin garantia,Libre inversión,Más de 3 años y hasta 5 años,29.36,0.0,1.249302e+11,4902,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36186244,1,BC-ESTABLECIMIENTO BANCARIO,39,Banco Davivienda,2022-09-09T00:00:00.000,Natural,Masculino,No aplica,Consumo,Sin garantia,Libre inversión,Más de 3 años y hasta 5 años,29.53,0.0,1.340866e+11,5303,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33257809,1,BC-ESTABLECIMIENTO BANCARIO,39,Banco Davivienda,2022-09-16T00:00:00.000,Natural,Masculino,No aplica,Consumo,Sin garantia,Libre inversión,Más de 3 años y hasta 5 años,29.85,0.0,1.490420e+11,5571,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
encontrado

,tipo_entidad,nombre_tipo_entidad,codigo_entidad,nombre_entidad,fecha_corte,tipo_de_persona,sexo,tama_o_de_empresa,tipo_de_cr_dito,tipo_de_garant_a,producto_de_cr_dito,plazo_de_cr_dito,tasa_efectiva_promedio,margen_adicional_a_la,montos_desembolsados,numero_de_creditos,grupo_etnico,antiguedad_de_la_empresa,tipo_de_tasa,rango_monto_desembolsado,clase_deudor,codigo_ciiu,codigo_municipio
9376909,1,BC-ESTABLECIMIENTO BANCARIO,7,Bancolombia,2025-01-31T00:00:00.000,Natural,Trans,No aplica,Consumo,Sin garantia,Tarjeta de crédito para ingresos superiores a ...,Consumos entre 2 y 6 meses,24.82,0.00,149966.0,4,Sin información (1),No aplica(1),FS,Hasta 1 SMLMV,Deudor nuevo en la entidad,10.0,73585.0
9377053,1,BC-ESTABLECIMIENTO BANCARIO,7,Bancolombia,2025-01-31T00:00:00.000,Natural,Trans,No aplica,Consumo,Sin garantia,Tarjeta de crédito para ingresos superiores a ...,Consumos entre 2 y 6 meses,24.82,0.00,923768.0,3,Sin información (1),No aplica(1),FS,Hasta 1 SMLMV,Deudor de la entidad,10.0,5001.0
9377197,1,BC-ESTABLECIMIENTO BANCARIO,7,Bancolombia,2025-01-31T00:00:00.000,Natural,Trans,No aplica,Consumo,Sin garantia,Tarjeta de crédito para ingresos superiores a ...,Consumos entre 2 y 6 meses,24.82,0.00,1648000.0,1,Sin información (1),No aplica(1),FS,Mayor a 1 SMLMV menor o igual a 3 SMLMV,Deudor de la entidad,10.0,5001.0
9382256,1,BC-ESTABLECIMIENTO BANCARIO,7,Bancolombia,2024-12-20T00:00:00.000,Natural,Trans,No aplica,Consumo,Sin garantia,Tarjeta de crédito para ingresos superiores a ...,Consumos entre 2 y 6 meses,26.31,0.00,252590.0,7,Sin información (1),No aplica(1),FS,Hasta 1 SMLMV,Deudor nuevo en la entidad,10.0,73585.0
9382400,1,BC-ESTABLECIMIENTO BANCARIO,7,Bancolombia,2024-12-20T00:00:00.000,Natural,Trans,No aplica,Consumo,Sin garantia,Tarjeta de crédito para ingresos superiores a ...,Consumos entre 2 y 6 meses,26.31,0.00,495000.0,2,Sin información (1),No aplica(1),FS,Hasta 1 SMLMV,Deudor de la entidad,10.0,5001.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44679178,1,BC-ESTABLECIMIENTO BANCARIO,7,Bancolombia,2024-02-02T00:00:00.000,Natural,Femenino,Microempresa,Comercial ordinario,Sin garantia,Empresarial en pesos,Más de 1 año y hasta 3 años,26.53,0.00,12400000.0,1,Sin información (1),más de 10 años,FS,Mayor a 6 SMLMV y menor o igual a 12 SMLMV,Deudor nuevo en la entidad,2511.0,85410.0
44679188,1,BC-ESTABLECIMIENTO BANCARIO,7,Bancolombia,2024-04-26T00:00:00.000,Natural,Femenino,Microempresa,Comercial ordinario,Garantía fondo nacional de garantías (FNG) o ...,Empresarial en pesos,Más de 30 días y hasta 1 año,15.52,4.44,113000000.0,1,Sin información (1),más de 10 años,DTF,Mayor a 50 SMLMV y menor o igual a 100 SMLMV,Deudor de la entidad,4731.0,13001.0
44679207,1,BC-ESTABLECIMIENTO BANCARIO,7,Bancolombia,2024-01-12T00:00:00.000,Natural,Femenino,Microempresa,Comercial ordinario,Garantía fondo nacional de garantías (FNG) o ...,Empresarial en pesos,Más de 1 año y hasta 3 años,22.00,8.20,50000000.0,1,Sin información (1),0 a 5 años,IB1,Mayor a 25 SMLMV y menor o igual a 50 SMLMV,Deudor de la entidad,4923.0,73001.0
44679208,1,BC-ESTABLECIMIENTO BANCARIO,7,Bancolombia,2024-01-26T00:00:00.000,Natural,Femenino,Microempresa,Comercial ordinario,Sin garantia,Factoring,Más de 30 días y hasta 1 año,16.60,4.25,8650395.0,10,Sin información (1),más de 10 años,DTF,Hasta 1 SMLMV,Deudor de la entidad,4722.0,8001.0
44679209,1,BC-ESTABLECIMIENTO BANCARIO,7,Bancolombia,2024-04-12T00:00:00.000,Natural,Femenino,Microempresa,Comercial ordinario,Garantía fondo nacional de garantías (FNG) o ...,Empresarial en pesos,Más de 1 año y hasta 3 años,19.98,0.00,35000000.0,1,Sin información (1),más de 10 años,FS,Mayor a 25 SMLMV y menor o igual a 50 SMLMV,Deudor de la entidad,1399.0,5001.0

In [ ]:
data.loc[data['nombre_entidad'] == 'Banco de Bogotá']

,tipo_entidad,nombre_tipo_entidad,codigo_entidad,nombre_entidad,fecha_corte,tipo_de_persona,sexo,tama_o_de_empresa,tipo_de_cr_dito,tipo_de_garant_a,producto_de_cr_dito,plazo_de_cr_dito,tasa_efectiva_promedio,margen_adicional_a_la,montos_desembolsados,numero_de_creditos,grupo_etnico,antiguedad_de_la_empresa,tipo_de_tasa,rango_monto_desembolsado,clase_deudor,codigo_ciiu,codigo_municipio
18847932,1,BC-ESTABLECIMIENTO BANCARIO,1,Banco de Bogotá,2024-12-06T00:00:00.000,Jurídica,No aplica,Mediana empresa,Comercial ordinario,Sin garantia,Empresarial en pesos,Más de 5 años y hasta 7 años,14.37,4.5,328000000.0,1,No aplica,más de 10 años,IB1,Mayor a 240 SMLMV y menor o igual a 480 SMLMV,Deudor nuevo en la entidad,4921.0,76001.0
18848076,1,BC-ESTABLECIMIENTO BANCARIO,1,Banco de Bogotá,2024-12-06T00:00:00.000,Jurídica,No aplica,Mediana empresa,Comercial ordinario,Sin garantia,Empresarial en pesos,Más de 5 años y hasta 7 años,14.37,4.5,450000000.0,1,No aplica,más de 10 años,IB1,Mayor a 240 SMLMV y menor o igual a 480 SMLMV,Deudor nuevo en la entidad,4530.0,8001.0
18848220,1,BC-ESTABLECIMIENTO BANCARIO,1,Banco de Bogotá,2025-03-14T00:00:00.000,Jurídica,No aplica,Mediana empresa,Comercial ordinario,Sin garantia,Factoring,Más de 30 días y hasta 1 año,11.11,0.0,10453500.0,1,No aplica,más de 10 años,IB1,Mayor a 6 SMLMV y menor o igual a 12 SMLMV,Deudor nuevo en la entidad,4649.0,19142.0
18848364,1,BC-ESTABLECIMIENTO BANCARIO,1,Banco de Bogotá,2025-03-14T00:00:00.000,Jurídica,No aplica,Mediana empresa,Comercial ordinario,Sin garantia,Factoring,Más de 30 días y hasta 1 año,11.18,0.0,1337225.0,2,No aplica,más de 10 años,FS,Hasta 1 SMLMV,Deudor nuevo en la entidad,4690.0,5360.0
18848508,1,BC-ESTABLECIMIENTO BANCARIO,1,Banco de Bogotá,2025-03-14T00:00:00.000,Jurídica,No aplica,Mediana empresa,Comercial ordinario,Sin garantia,Factoring,Más de 30 días y hasta 1 año,11.18,0.0,2073405.0,1,No aplica,más de 10 años,FS,Mayor a 1 SMLMV y menor o igual a 3 SMLMV,Deudor nuevo en la entidad,4690.0,5360.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44679170,1,BC-ESTABLECIMIENTO BANCARIO,1,Banco de Bogotá,2024-03-29T00:00:00.000,Natural,Femenino,Microempresa,Comercial ordinario,Sin garantia,Tarjeta de crédito empresarial,Consumos entre 25 y 36 meses,33.27,0.0,5083566.0,2,Sin información (1),No aplica(1),FS,Mayor a 1 SMLMV menor o igual a 3 SMLMV,Deudor nuevo en la entidad,4771.0,5001.0
44679186,1,BC-ESTABLECIMIENTO BANCARIO,1,Banco de Bogotá,2023-12-01T00:00:00.000,Natural,Femenino,Microempresa,Comercial ordinario,Sin garantia,Tarjeta de crédito empresarial,Avances en efectivo,38.25,0.0,1200000.0,1,Sin información (1),No aplica(1),FS,Mayor a 1 SMLMV menor o igual a 3 SMLMV,Deudor nuevo en la entidad,10.0,76130.0
44679187,1,BC-ESTABLECIMIENTO BANCARIO,1,Banco de Bogotá,2024-05-24T00:00:00.000,Natural,Femenino,Microempresa,Comercial ordinario,Sin garantia,Tarjeta de crédito empresarial,Avances en efectivo,31.50,0.0,1200000.0,2,Sin información (1),No aplica(1),FS,Hasta 1 SMLMV,Deudor nuevo en la entidad,10.0,25290.0
44679190,1,BC-ESTABLECIMIENTO BANCARIO,1,Banco de Bogotá,2024-07-05T00:00:00.000,Natural,Femenino,Microempresa,Comercial ordinario,Sin garantia,Tarjeta de crédito empresarial,Avances en efectivo,29.46,0.0,1000000.0,1,Sin información (1),No aplica(1),FS,Hasta 1 SMLMV,Deudor nuevo en la entidad,10.0,5001.0
44679200,1,BC-ESTABLECIMIENTO BANCARIO,1,Banco de Bogotá,2024-07-26T00:00:00.000,Natural,Femenino,Microempresa,Comercial ordinario,Sin garantia,Tarjeta de crédito empresarial,Consumos a un mes,0.00,0.0,200000.0,1,Sin información (1),No aplica(1),FS,Hasta 1 SMLMV,Deudor nuevo en la entidad,4649.0,5615.0